from rdflib.namespace import Namespace, NamespaceManager
from rdflib import Graph

IFC_MODEL = Namespace("https://secorolab.github.io/models/ifc-model#")
IFC_CLASS = Namespace(
    "https://identifier.buildingsmart.org/uri/buildingsmart/ifc/4.3/class/"
)
IFC_PROP = Namespace(
    "https://identifier.buildingsmart.org/uri/buildingsmart/ifc/4.3/prop/"
)
IFC_CONCEPTS = Namespace("https://secorolab.github.io/metamodels/ifc/")
QUDT_QUANT = Namespace("http://qudt.org/vocab/quantitykind/")
QUDT_UNIT = Namespace("http://qudt.org/vocab/unit/")
QUDT_PREFIX = Namespace("http://qudt.org/vocab/prefix/")
QUDT_SCHEMA = Namespace("http://qudt.org/schema/qudt/")

namespace_manager = NamespaceManager(Graph())
namespace_manager.bind("ifc", IFC_CONCEPTS, override=True)
namespace_manager.bind("ifc-class", IFC_CLASS, override=True)
namespace_manager.bind("ifc-prop", IFC_PROP, override=True)
namespace_manager.bind("ifc-model", IFC_MODEL, override=True)
namespace_manager.bind("qudt-schema", QUDT_SCHEMA, override=True)
namespace_manager.bind("qudt-quant", QUDT_QUANT, override=True)
namespace_manager.bind("qudt-unit", QUDT_UNIT, override=True)

MEASURES = {
    "IFCABSORBEDDOSEMEASURE": "AbsorbedDose",
    "IFCAMOUNTOFSUBSTANCEMEASURE": "AmountOfSubstance",
    "IFCAREAMEASURE": "Area",
    "IFCDOSEEQUIVALENTMEASURE": "DoseEquivalent",
    "IFCELECTRICCAPACITANCEMEASURE": "Capacitance",
    "IFCELECTRICCHARGEMEASURE": "ElectricCharge",
    "IFCELECTRICCONDUCTANCEMEASURE": "ElectricConductivity",
    "IFCELECTRICCURRENTMEASURE": "ElectricCurrent",
    "IFCELECTRICRESISTANCEMEASURE": "Resistance",
    "IFCELECTRICVOLTAGEMEASURE": "Voltage",
    "IFCENERGYMEASURE": "Energy",
    "IFCFORCEMEASURE": "Force",
    "IFCFREQUENCYMEASURE": "Frequency",
    "IFCILLUMINANCEMEASURE": "Illuminance",
    "IFCINDUCTANCEMEASURE": "Inductance",
    "IFCLENGTHMEASURE": "Length",
    "IFCLUMINOUSFLUXMEASURE": "LuminousFlux",
    "IFCLUMINOUSINTENSITYMEASURE": "LuminousIntensity",
    "IFCMAGNETICFLUXDENSITYMEASURE": "MagneticFluxDensity",
    "IFCMAGNETICFLUXMEASURE": "MagneticFlux",
    "IFCMASSMEASURE": "Mass",
    "IFCPLANEANGLEMEASURE": "PlaneAngle",
    "IFCPOWERMEASURE": "Power",
    "IFCPRESSUREMEASURE": "Pressure",
    "IFCRADIOACTIVITYMEASURE": "Activity",
    "IFCSOLIDANGLEMEASURE": "SolidAngle",
    "IFCTHERMODYNAMICTEMPERATUREMEASURE": "ThermodynamicTemperature",
    "IFCTIMEMEASURE": "Time",
    "IFCVOLUMEMEASURE": "Volume",
    "IFCANGULARVELOCITYMEASURE": "AngularVelocity",
    "IFCAREADENSITYMEASURE": "SurfaceDensity",
    "IFCCOMPOUNDPLANEANGLEMEASURE": "PlaneAngle",
    "IFCDYNAMICVISCOSITYMEASURE": "DynamicViscosity",
    "IFCHEATFLUXDENSITYMEASURE": "HeatFluxDensity",
    "IFCINTEGERCOUNTRATEMEASURE": "Frequency",
    "IFCKINEMATICVISCOSITYMEASURE": "KinematicViscosity",
    "IFCLINEARVELOCITYMEASURE": "LinearVelocity",
    "IFCMASSDENSITYMEASURE": "MassDensity",
    "IFCMASSFLOWRATEMEASURE": "MassFlowRate",
    "IFCMOLECULARWEIGHTMEASURE": "MolarMass",
    "IFCSPECIFICHEATCAPACITYMEASURE": "SpecificHeatCapacity",
    "IFCTHERMALCONDUCTANCEMEASURE": "ThermalConductance",
    "IFCTHERMALRESISTANCEMEASURE": "ThermalResistance",
    "IFCVOLUMETRICFLOWRATEMEASURE": "VolumeFlowRate",
    "IFCROTATIONALFREQUENCYMEASURE": "AngularFrequency",
    "IFCTORQUEMEASURE": "Torque",
    "IFCMOMENTOFINERTIAMEASURE": "MomentOfInertia",
    "IFCLINEARMOMENTMEASURE": "LinearMomentum",
    "IFCMODULUSOFELASTICITYMEASURE": "ModulusOfElasticity",
    "IFCSHEARMODULUSMEASURE": "ShearModulus",
    "IFCACCELERATIONMEASURE": "Acceleration",
    "IFCCURVATUREMEASURE": "Curvature",
    "IFCMASSPERLENGTHMEASURE": "MassPerLength",
    "IFCROTATIONALMASSMEASURE": "RotationalMass",
    "IFCSECTIONMODULUSMEASURE": "SectionModulus",
    "IFCSOUNDPOWERLEVELMEASURE": "SoundPowerLevel",
    "IFCSOUNDPOWERMEASURE": "SoundPower",
    "IFCSOUNDPRESSURELEVELMEASURE": "SoundPressureLevel",
    "IFCSOUNDPRESSUREMEASURE": "SoundPressure",
    "IFCTEMPERATURERATEOFCHANGEMEASURE": "TemperatureRateOfChange",
    "IFCTHERMALEXPANSIONCOEFFICIENTMEASURE": "ThermalExpansionCoefficient",
    "IFCISOTHERMALMOISTURECAPACITYMEASURE": "IsothermalMoistureCapacity",
    "IFCMOISTUREDIFFUSIVITYMEASURE": "MoistureDiffusivity",
    "IFCTHERMALADMITTANCEMEASURE": "ThermalAdmittance",
    "IFCTHERMALTRANSMITTANCEMEASURE": "ThermalTransmittance",
    "IFCVAPORPERMEABILITYMEASURE": "VaporPermeability",
    "IFCLINEARFORCEMEASURE": "LinearForce",
    "IFCPLANARFORCEMEASURE": "PlanarForce",
    "IFCLINEARSTIFFNESSMEASURE": "LinearStiffness",
    "IFCROTATIONALSTIFFNESSMEASURE": "RotationalStiffness",
    "IFCMODULUSOFSUBGRADEREACTIONMEASURE": "ModulusOfSubgradeReaction",
    "IFCHEATINGVALUEMEASURE": "HeatingValue",
    "IFCIONCONCENTRATIONMEASURE": "IonConcentration",
    "IFCLUMINOUSINTENSITYDISTRIBUTIONMEASURE": "LuminousIntensityDistribution",
    "IFCMODULUSOFLINEARSUBGRADEREACTIONMEASURE": "ModulusOfLinearSubgradeReaction",
    "IFCMODULUSOFROTATIONALSUBGRADEREACTIONMEASURE": "ModulusOfRotationalSubgradeReaction",
    "IFCPHMEASURE": "PH",
    "IFCSECTIONAREAINTEGRALMEASURE": "SectionAreaIntegral",
    "IFCTEMPERATUREGRADIENTMEASURE": "TemperatureGradient",
    "IFCWARPINGCONSTANTMEASURE": "WarpingConstant",
    "IFCWARPINGMOMENTMEASURE": "WarpingMoment",
    "IFCRATIOMEASURE": "DimensionlessRatio",
    "IFCPOSITIVERATIOMEASURE": "PositiveDimensionlessRatio",
    "IFCNORMALISEDRATIOMEASURE": "NormalizedDimensionlessRatio",
    "IFCNUMERICMEASURE": "Dimensionless",
    "IFCNONNEGATIVELENGTHMEASURE": "NonNegativeLength",
    "IFCPOSITIVELENGTHMEASURE": "PositiveLength",
    "IFCPOSITIVEPLANEANGLEMEASURE": "PositivePlaneAngle",
    "IFCCOUNTMEASURE": "Count",
    "IFCTHERMALCONDUCTIVITYMEASURE": QUDT_QUANT["ThermalConductivity"],
}

UNIT_TYPES = {
    "AREAUNIT": "Area",
    "ABSORBEDDOSEUNIT": "AbsorbedDose",
    "AMOUNTOFSUBSTANCEUNIT": "AmountOfSubstance",
    "DOSEEQUIVALENTUNIT": "DoseEquivalent",
    "ELECTRICCAPACITANCEUNIT": "ElectricCapacitance",
    "ELECTRICCHARGEUNIT": "ElectricCharge",
    "ELECTRICCONDUCTANCEUNIT": "ElectricConductance",
    "ELECTRICCURRENTUNIT": "ElectricCurrent",
    "ELECTRICRESISTANCEUNIT": "ElectricResistance",
    "ELECTRICVOLTAGEUNIT": "ElectricVoltage",
    "ENERGYUNIT": "Energy",
    "FORCEUNIT": "Force",
    "FREQUENCYUNIT": "Frequency",
    "ILLUMINANCEUNIT": "Illuminance",
    "INDUCTANCEUNIT": "Inductance",
    "LENGTHUNIT": "Length",
    "LUMINOUSFLUXUNIT": "LuminousFlux",
    "LUMINOUSINTENSITYUNIT": "LuminousIntensity",
    "MAGNETICFLUXDENSITYUNIT": "MagneticFluxDensity",
    "MAGNETICFLUXUNIT": "MagneticFlux",
    "MASSUNIT": "Mass",
    "PLANEANGLEUNIT": "PlaneAngle",
    "POWERUNIT": "Power",
    "PRESSUREUNIT": "Pressure",
    "RADIOACTIVITYUNIT": "Radioactivity",
    "SOLIDANGLEUNIT": "SolidAngle",
    "THERMODYNAMICTEMPERATUREUNIT": "ThermodynamicTemperature",
    "TIMEUNIT": "Time",
    "VOLUMEUNIT": "Volume",
    "USERDEFINED": "UserDefined",
}

UNITS = {
    "AMPERE": "A",
    "BECQUEREL": "BQ",
    "CANDELA": "CD",
    "COULOMB": "C",
    "CUBIC_METRE": "M3",
    "DEGREE_CELSIUS": "DEG_C",
    "FARAD": "F",
    "GRAM": "GM",
    "GRAY": "GRAY",
    "HENRY": "H",
    "HERTZ": "HZ",
    "JOULE": "J",
    "KELVIN": "K",
    "LUMEN": "LM",
    "LUX": "LUX",
    "METRE": "M",
    "MOLE": "MOL",
    "NEWTON": "N",
    "OHM": "OHM",
    "PASCAL": "PA",
    "RADIAN": "RAD",
    "SECOND": "SEC",
    "SIEMENS": "S",
    "SIEVERT": "SV",
    "SQUARE_METRE": "M2",
    "STERADIAN": "SR",
    "TESLA": "T",
    "VOLT": "V",
    "WATT": "W",
    "WEBER": "WB",
    # Non-SI Units
    "DEGREE": "DEG",
    "FOOT": "FT",
    "SQUARE FOOT": "FT2",
    "CUBIC FOOT": "FT3",
    "INCH": "IN",
    "SQUARE INCH": "IN2",
    "CUBIC INCH": "IN3",
    "YEAR": "YR",
    "KIP": "KIP_F",
}

PREFIXES = {
    "ATTO": "Atto",
    "CENTI": "Centi",
    "DECA": "Deca",
    "DECI": "Deci",
    "EXA": "Exa",
    "FEMTO": "Femto",
    "GIGA": "Giga",
    "HECTO": "Hecto",
    "KILO": "Kilo",
    "MEGA": "Mega",
    "MICRO": "Micro",
    "MILLI": "Milli",
    "NANO": "Nano",
    "PETA": "Peta",
    "PICO": "Pico",
    "TERA": "Tera",
}
